export const chats = [
	{
		id: 1,
		userId: 1,
		firstName: "Тимур",
		secondName: "Киселев",
		isPinned: true,
		isActive: true,
		isTyping: false,
		photo: "/photo.png",
		isMutedOff: false,
		position: "Менеджер по работе с клиентами",
		isGroupChat: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		dateRangeStart: "2020-05-03T16:34:09.000000Z",
		dateRangeEnd: "2024-03-17T16:34:09.000000Z",
		messages: [
			{
				id: 6,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: false,
				isViewed: false,
				isUnread: false,
				date: "05.03.2020 15:12",
			},
			{
				id: 6,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: false,
				isViewed: false,
				isUnread: false,
				date: "05.04.2021 15:12",
			},
			{
				id: 6,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: false,
				isViewed: false,
				isUnread: false,
				date: "05.01.2022 15:12",
			},
			{
				id: 1,
				type: "text",
				message: "Привет Привет ПриветПриветПривет ПриветПривет ПриветПриветПривет Привет Привет ПриветПривет Привет",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "14.05.2023 15:12",
			},
			{
				id: 2,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "14.02.2024 15:12",
			},
			{
				id: 1,
				type: "text",
				message: "Привет",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "14.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "14.02.2024 15:12",
			},
			{
				id: 1,
				type: "text",
				message: "Привет",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "16.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "16.02.2024 15:12",
			},
			{
				id: 3,
				type: "text",
				message: "Привет",
				userId: 2,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "16.02.2024 15:12",
			},
			{
				id: 4,
				type: "text",
				message: "Принимаете заказ?",
				userId: 2,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "16.02.2024 15:12",
			},
			{
				id: 5,
				type: "text",
				message: "Привет",
				userId: 1,
				isReceived: true,
				isViewed: false,
				isUnread: false,
				date: "29.02.2024 15:12",
			},
			{
				id: 6,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: false,
				isViewed: false,
				isUnread: false,
				date: "05.03.2024 15:12",
			},
			{
				id: 7,
				type: "image",
				comment: "",
				userId: 2,
				isReceived: false,
				isViewed: false,
				isUnread: false,
				date: "15.03.2024 15:12",
				images: [
					{
						url: "/image-example.png",
						filename: "image-example.png",
						date: "15.03.2024 15:12",
						isReceived: true,
						isViewed: true,
						isUnread: false,
					},
					{
						url: "/image-example.png",
						filename: "image-example.png",
						date: "15.03.2024 15:12",
						isReceived: true,
						isViewed: true,
						isUnread: false,
					},
				],
			},
			{
				id: 8,
				type: "image",
				comment: "Прикрепляю фото",
				userId: 1,
				isReceived: true,
				isViewed: false,
				isUnread: false,
				date: "15.03.2024 15:12",
				images: [
					{
						filename: "image-example.png",
						url: "/image-example.png",
						date: "15.03.2024 15:12",
						isReceived: true,
						isViewed: true,
						isUnread: false,
					},
				],
			},
			{
				id: 9,
				type: "file",
				comment: "Пример отображения загруженных файлов",
				userId: 2,
				isReceived: true,
				isViewed: false,
				isUnread: false,
				date: "17.03.2024 15:12",
				files: [
					{
						url: "",
						fileName: "Длинный пример имени файла в формате docx для обрезки.docx",
						date: "17.03.2024 15:12",
						isReceived: true,
						isViewed: true,
						isUnread: false,
						size: "15KB",
					},
					{
						url: "",
						fileName: "Пример имени.xls",
						date: "17.03.2024 15:23",
						isReceived: true,
						isViewed: true,
						isUnread: false,
						size: "7KB",
					},
				],
			},
			{
				id: 10,
				type: "file",
				comment: "",
				userId: 1,
				isReceived: true,
				isViewed: false,
				isUnread: false,
				date: "17.03.2024 15:12",
				files: [
					{
						url: "",
						fileName: "Полезный файл.pdf",
						date: "17.03.2024 17:12",
						isReceived: true,
						isViewed: true,
						isUnread: false,
						size: "22KB",
					},
				],
			},
		],
	},
	{
		id: 1165431,
		isGroupChat: true,
		title: "Логистика",
		photo: "",
		isPinned: true,
		isTyping: false,
		isMutedOff: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		textMessageDraft: "",
		users: [
			{
				userId: 2,
				firstName: "Женя",
				secondName: "Иванов",
				isActive: true,
				isTyping: false,
				photo: "/photo.png",
				position: "Менеджер по работе с клиентами",
				lastTimeActive: "15.02.2024 15:00",
			},
			{
				userId: 3,
				firstName: "Арсений",
				secondName: "Голубев",
				isActive: false,
				isTyping: false,
				photo: "",
				position: "Менеджер",
				lastTimeActive: "20.02.2024 14:00",
			},
			{
				userId: 4,
				firstName: "Илья",
				secondName: "Петров",
				isActive: true,
				isTyping: false,
				photo: "/photo.png",
				position: "Менеджер по работе с клиентами",
				lastTimeActive: "20.02.2024 14:00",
			},
		],
		dateRangeStart: "2024-02-14T16:34:09.000000Z",
		dateRangeEnd: "2024-03-08T16:34:09.000000Z",
		messages: [
			{
				id: 33,
				type: "message-info",
				message: "Тимур Киселев создал групповой чат",
				date: "14.02.2024 15:12",
			},
			{
				id: 1,
				type: "text",
				userId: 1,
				firstName: "Тимур",
				secondName: "Киселев",
				message: "Добрый день, коллеги",
				date: "14.02.2024 15:12",
			},
			{
				id: 2,
				userId: 2,
				type: "text",
				firstName: "Илья",
				secondName: "Петров",
				message: "Добрый день",
				date: "08.03.2024 15:12",
			},
			{
				id: 2,
				userId: 2,
				type: "text",
				firstName: "Илья",
				secondName: "Петров",
				message: "Добрый день",
				date: "08.03.2024 15:12",
			},
		],
	},
	{
		id: 2656542,
		userId: 2,
		firstName: "Женя",
		secondName: "Иванов",
		isPinned: true,
		isActive: true,
		isTyping: false,
		photo: undefined,
		isMutedOff: true,
		position: "Менеджер по работе с клиентами",
		isGroupChat: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		dateRangeStart: "2024-02-14T16:34:09.000000Z",
		dateRangeEnd: "2024-02-14T16:34:09.000000Z",
		messages: [
			{
				id: 1,
				type: "text",
				message: "Привет",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: true,
				date: "14.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: true,
				date: "14.02.2024 15:12",
			},
			{
				id: 3,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: true,
				date: "14.02.2024 15:12",
			},
			{
				id: 4,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: true,
				date: "14.02.2024 15:12",
			},
			{
				id: 5,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: true,
				date: "14.02.2024 15:12",
			},
		],
	},
	{
		id: 3,
		userId: 3,
		firstName: "Арсений",
		secondName: "Баранов",
		isPinned: false,
		isActive: true,
		isTyping: false,
		photo: undefined,
		isMutedOff: false,
		position: "Менеджер по работе с клиентами",
		isGroupChat: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		dateRangeStart: "2024-02-14T16:34:09.000000Z",
		dateRangeEnd: "2024-02-14T16:34:09.000000Z",
		messages: [
			{
				id: 1,
				type: "text",
				message: "Привет",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "14.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "14.02.2024 15:12",
			},
		],
	},
	{
		id: 4,
		userId: 4,
		firstName: "Илья",
		secondName: "Петров",
		isPinned: false,
		isActive: false,
		isTyping: false,
		photo: undefined,
		isMutedOff: false,
		position: "",
		isGroupChat: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		dateRangeStart: "2024-02-14T16:34:09.000000Z",
		dateRangeEnd: "2024-02-14T16:34:09.000000Z",
		messages: [
			{
				id: 1,
				type: "text",
				message: "Привет",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "14.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "14.02.2024 15:12",
			},
		],
	},
	{
		id: 6,
		userId: 6,
		firstName: "Тимур",
		secondName: "Киселев",
		isPinned: false,
		isActive: false,
		isTyping: false,
		photo: "/photo.png",
		isMutedOff: false,
		position: "",
		isGroupChat: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		dateRangeStart: "2024-02-13T16:34:09.000000Z",
		dateRangeEnd: "2024-02-13T16:34:09.000000Z",
		messages: [
			{
				id: 1,
				type: "text",
				message: "Привет",
				userId: 6,
				isReceived: true,
				isViewed: true,
				isUnread: true,
				date: "13.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				message: "Принимаете заказ?",
				userId: 6,
				isReceived: true,
				isViewed: true,
				isUnread: true,
				date: "13.02.2024 15:12",
			},
		],
	},
	{
		id: 73464,
		userId: 7,
		firstName: "Тимур",
		secondName: "Киселев",
		isPinned: false,
		isActive: true,
		isTyping: true,
		photo: "/photo.png",
		isMutedOff: true,
		position: "Менеджер по работе с клиентами",
		isGroupChat: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		dateRangeStart: "",
		dateRangeEnd: "",
		messages: [],
	},
	{
		id: 12435,
		isGroupChat: true,
		title: "Праздники 🤩",
		photo: "",
		isPinned: false,
		isTyping: false,
		isMutedOff: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		users: [
			{
				id: 2,
				type: "text",
				firstName: "Илья",
				secondName: "Петров",
				isActive: true,
				isTyping: false,
				lastTimeActive: "15.02.2024 15:00",

				photo: "/photo.png",
				position: "Менеджер по работе с клиентами",
			},
			{
				id: 3,
				type: "text",
				firstName: "Вася",
				secondName: "Петров",
				isActive: false,
				lastTimeActive: "15.02.2024 15:00",

				isTyping: false,
				photo: "",
				position: "Менеджер",
			},
		],
		dateRangeStart: "2024-02-14T16:34:09.000000Z",
		dateRangeEnd: "2024-02-14T16:34:09.000000Z",
		messages: [
			{
				id: 1,
				userId: 1,
				firstName: "Тимур",
				secondName: "Киселев",
				message: "Сдаем на праздник",
				date: "14.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				userId: 2,
				firstName: "Илья",
				secondName: "Петров",
				message: "Несу",
				date: "14.02.2024 15:12",
			},
		],
	},
	{
		id: 83445,
		userId: 8,
		firstName: "Тимур",
		secondName: "Киселев",
		isPinned: false,
		isActive: true,
		isTyping: false,
		photo: undefined,
		isMutedOff: false,
		position: "Менеджер",
		isGroupChat: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		dateRangeStart: "",
		dateRangeEnd: "",
		messages: [],
	},
	{
		id: 9,
		userId: 9,
		firstName: "Тимур",
		secondName: "Киселев",
		isPinned: false,
		isActive: true,
		isTyping: false,
		photo: undefined,
		isMutedOff: false,
		position: "Менеджер",
		isGroupChat: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		dateRangeStart: "2024-02-14T16:34:09.000000Z",
		dateRangeEnd: "2024-02-14T16:34:09.000000Z",
		messages: [
			{
				id: 1,
				type: "text",
				message: "Привет",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: true,
				date: "14.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: true,
				date: "14.02.2024 15:12",
			},
		],
	},
	{
		id: 104332432,
		userId: 10,
		firstName: "Тимур",
		secondName: "Киселев",
		isPinned: false,
		isActive: true,
		isTyping: false,
		photo: undefined,
		isMutedOff: false,
		position: "Менеджер",
		isGroupChat: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		dateRangeStart: "2024-02-14T16:34:09.000000Z",
		dateRangeEnd: "2024-02-14T16:34:09.000000Z",
		messages: [
			{
				id: 1,
				type: "text",
				message: "Привет",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "14.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: false,
				isViewed: false,
				isUnread: true,
				date: "14.02.2024 15:12",
			},
		],
	},
	{
		id: 345334,
		userId: 1,
		firstName: "Тимур",
		secondName: "Киселев",
		isPinned: true,
		isActive: true,
		isTyping: false,
		photo: "/photo.png",
		isMutedOff: false,
		position: "Менеджер по работе с клиентами",
		isGroupChat: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		dateRangeStart: "2024-02-14T16:34:09.000000Z",
		dateRangeEnd: "2024-03-17T16:34:09.000000Z",
		messages: [
			{
				id: 1,
				type: "text",
				message: "Привет Привет ПриветПриветПривет ПриветПривет ПриветПриветПривет Привет Привет ПриветПривет Привет",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "14.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "14.02.2024 15:12",
			},
			{
				id: 1,
				type: "text",
				message: "Привет",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "14.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "14.02.2024 15:12",
			},
			{
				id: 1,
				type: "text",
				message: "Привет",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "16.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "16.02.2024 15:12",
			},
			{
				id: 3,
				type: "text",
				message: "Привет",
				userId: 2,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "16.02.2024 15:12",
			},
			{
				id: 4,
				type: "text",
				message: "Принимаете заказ?",
				userId: 2,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "16.02.2024 15:12",
			},
			{
				id: 5,
				type: "text",
				message: "Привет",
				userId: 1,
				isReceived: true,
				isViewed: false,
				isUnread: false,
				date: "29.02.2024 15:12",
			},
			{
				id: 6,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: false,
				isViewed: false,
				isUnread: false,
				date: "05.03.2024 15:12",
			},
			{
				id: 7,
				type: "image",
				comment: "",
				userId: 2,
				isReceived: false,
				isViewed: false,
				isUnread: false,
				date: "15.03.2024 15:12",
				images: [
					{
						url: "/image-example.png",
						filename: "image-example.png",
						date: "15.03.2024 15:12",
						isReceived: true,
						isViewed: true,
						isUnread: false,
					},
					{
						url: "/image-example.png",
						filename: "image-example.png",
						date: "15.03.2024 15:12",
						isReceived: true,
						isViewed: true,
						isUnread: false,
					},
				],
			},
			{
				id: 8,
				type: "image",
				comment: "Прикрепляю фото",
				userId: 1,
				isReceived: true,
				isViewed: false,
				isUnread: false,
				date: "15.03.2024 15:12",
				images: [
					{
						filename: "image-example.png",
						url: "/image-example.png",
						date: "15.03.2024 15:12",
						isReceived: true,
						isViewed: true,
						isUnread: false,
					},
				],
			},
			{
				id: 9,
				type: "file",
				comment: "Пример отображения загруженных файлов",
				userId: 2,
				isReceived: true,
				isViewed: false,
				isUnread: false,
				date: "17.03.2024 15:12",
				files: [
					{
						url: "",
						fileName: "Длинный пример имени файла в формате docx для обрезки.docx",
						date: "17.03.2024 15:12",
						isReceived: true,
						isViewed: true,
						isUnread: false,
						size: "15KB",
					},
					{
						url: "",
						fileName: "Пример имени.xls",
						date: "17.03.2024 15:23",
						isReceived: true,
						isViewed: true,
						isUnread: false,
						size: "7KB",
					},
				],
			},
			{
				id: 10,
				type: "file",
				comment: "",
				userId: 1,
				isReceived: true,
				isViewed: false,
				isUnread: false,
				date: "17.03.2024 15:12",
				files: [
					{
						url: "",
						fileName: "Полезный файл.pdf",
						date: "17.03.2024 17:12",
						isReceived: true,
						isViewed: true,
						isUnread: false,
						size: "22KB",
					},
				],
			},
		],
	},
	{
		id: 11,
		isGroupChat: true,
		title: "Логистика",
		photo: "",
		isPinned: true,
		isTyping: false,
		isMutedOff: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		textMessageDraft: "",
		users: [
			{
				userId: 2,
				firstName: "Женя",
				secondName: "Иванов",
				isActive: true,
				isTyping: false,
				photo: "/photo.png",
				position: "Менеджер по работе с клиентами",
				lastTimeActive: "15.02.2024 15:00",
			},
			{
				userId: 3,
				firstName: "Арсений",
				secondName: "Голубев",
				isActive: false,
				isTyping: false,
				photo: "",
				position: "Менеджер",
				lastTimeActive: "20.02.2024 14:00",
			},
			{
				userId: 4,
				firstName: "Илья",
				secondName: "Петров",
				isActive: true,
				isTyping: false,
				photo: "/photo.png",
				position: "Менеджер по работе с клиентами",
				lastTimeActive: "20.02.2024 14:00",
			},
		],
		dateRangeStart: "2024-02-14T16:34:09.000000Z",
		dateRangeEnd: "2024-03-08T16:34:09.000000Z",
		messages: [
			{
				id: 33,
				type: "message-info",
				message: "Тимур Киселев создал групповой чат",
				date: "14.02.2024 15:12",
			},
			{
				id: 1,
				type: "text",
				userId: 1,
				firstName: "Тимур",
				secondName: "Киселев",
				message: "Добрый день, коллеги",
				date: "14.02.2024 15:12",
			},
			{
				id: 2,
				userId: 2,
				type: "text",
				firstName: "Илья",
				secondName: "Петров",
				message: "Добрый день",
				date: "08.03.2024 15:12",
			},
			{
				id: 2,
				userId: 2,
				type: "text",
				firstName: "Илья",
				secondName: "Петров",
				message: "Добрый день",
				date: "08.03.2024 15:12",
			},
		],
	},
	{
		id: 2,
		userId: 2,
		firstName: "Женя",
		secondName: "Иванов",
		isPinned: true,
		isActive: true,
		isTyping: false,
		photo: undefined,
		isMutedOff: true,
		position: "Менеджер по работе с клиентами",
		isGroupChat: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		dateRangeStart: "2024-02-14T16:34:09.000000Z",
		dateRangeEnd: "2024-02-14T16:34:09.000000Z",
		messages: [
			{
				id: 1,
				type: "text",
				message: "Привет",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: true,
				date: "14.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: true,
				date: "14.02.2024 15:12",
			},
			{
				id: 3,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: true,
				date: "14.02.2024 15:12",
			},
			{
				id: 4,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: true,
				date: "14.02.2024 15:12",
			},
			{
				id: 5,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: true,
				date: "14.02.2024 15:12",
			},
		],
	},
	{
		id: 64873,
		userId: 3,
		firstName: "Арсений",
		secondName: "Баранов",
		isPinned: false,
		isActive: true,
		isTyping: false,
		photo: undefined,
		isMutedOff: false,
		position: "Менеджер по работе с клиентами",
		isGroupChat: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		dateRangeStart: "2024-02-14T16:34:09.000000Z",
		dateRangeEnd: "2024-02-14T16:34:09.000000Z",
		messages: [
			{
				id: 1,
				type: "text",
				message: "Привет",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "14.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "14.02.2024 15:12",
			},
		],
	},
	{
		id: 456346,
		userId: 4,
		firstName: "Илья",
		secondName: "Петров",
		isPinned: false,
		isActive: false,
		isTyping: false,
		photo: undefined,
		isMutedOff: false,
		position: "",
		isGroupChat: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		dateRangeStart: "2024-02-14T16:34:09.000000Z",
		dateRangeEnd: "2024-02-14T16:34:09.000000Z",
		messages: [
			{
				id: 1,
				type: "text",
				message: "Привет",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "14.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "14.02.2024 15:12",
			},
		],
	},
	{
		id: 66346,
		userId: 6,
		firstName: "Тимур",
		secondName: "Киселев",
		isPinned: false,
		isActive: false,
		isTyping: false,
		photo: "/photo.png",
		isMutedOff: false,
		position: "",
		isGroupChat: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		dateRangeStart: "2024-02-13T16:34:09.000000Z",
		dateRangeEnd: "2024-02-13T16:34:09.000000Z",
		messages: [
			{
				id: 1,
				type: "text",
				message: "Привет",
				userId: 6,
				isReceived: true,
				isViewed: true,
				isUnread: true,
				date: "13.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				message: "Принимаете заказ?",
				userId: 6,
				isReceived: true,
				isViewed: true,
				isUnread: true,
				date: "13.02.2024 15:12",
			},
		],
	},
	{
		id: 7,
		userId: 7,
		firstName: "Тимур",
		secondName: "Киселев",
		isPinned: false,
		isActive: true,
		isTyping: true,
		photo: "/photo.png",
		isMutedOff: true,
		position: "Менеджер по работе с клиентами",
		isGroupChat: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		dateRangeStart: "",
		dateRangeEnd: "",
		messages: [],
	},
	{
		id: 12,
		isGroupChat: true,
		title: "Праздники 🤩",
		photo: "",
		isPinned: false,
		isTyping: false,
		isMutedOff: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		users: [
			{
				id: 2,
				type: "text",
				firstName: "Илья",
				secondName: "Петров",
				isActive: true,
				isTyping: false,
				photo: "/photo.png",
				position: "Менеджер по работе с клиентами",
				lastTimeActive: "20.02.2024 14:00",
			},
			{
				id: 3,
				type: "text",
				firstName: "Вася",
				secondName: "Петров",
				isActive: false,
				isTyping: false,
				photo: "",
				position: "Менеджер",
				lastTimeActive: "20.02.2024 14:00",
			},
		],
		dateRangeStart: "2024-02-14T16:34:09.000000Z",
		dateRangeEnd: "2024-02-14T16:34:09.000000Z",
		messages: [
			{
				id: 1,
				userId: 1,
				firstName: "Тимур",
				secondName: "Киселев",
				message: "Сдаем на праздник",
				date: "14.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				userId: 2,
				firstName: "Илья",
				secondName: "Петров",
				message: "Несу",
				date: "14.02.2024 15:12",
			},
		],
	},
	{
		id: 8,
		userId: 8,
		firstName: "Тимур",
		secondName: "Киселев",
		isPinned: false,
		isActive: true,
		isTyping: false,
		photo: undefined,
		isMutedOff: false,
		position: "Менеджер",
		isGroupChat: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		dateRangeStart: "",
		dateRangeEnd: "",
		messages: [],
	},
	{
		id: 433453455,
		userId: 9,
		firstName: "Тимур",
		secondName: "Киселев",
		isPinned: false,
		isActive: true,
		isTyping: false,
		photo: undefined,
		isMutedOff: false,
		position: "Менеджер",
		isGroupChat: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		dateRangeStart: "2024-02-14T16:34:09.000000Z",
		dateRangeEnd: "2024-02-14T16:34:09.000000Z",
		messages: [
			{
				id: 1,
				type: "text",
				message: "Привет",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: true,
				date: "14.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: true,
				date: "14.02.2024 15:12",
			},
		],
	},
	{
		id: 10,
		userId: 10,
		firstName: "Тимур",
		secondName: "Киселев",
		isPinned: false,
		isActive: true,
		isTyping: false,
		photo: undefined,
		isMutedOff: false,
		position: "Менеджер",
		isGroupChat: false,
		totalTextMessages: 200,
		totalPhotoMessages: 404,
		totalVideoMessages: 23,
		totalFileMessages: 19,
		totalVoiceMessages: 5,
		totalLinksMessages: 66,
		isMenuOpen: false,
		isDetailedInfoOpen: false,
		lastTimeActive: "15.02.2024 15:00",
		textMessageDraft: "",
		dateRangeStart: "2024-02-14T16:34:09.000000Z",
		dateRangeEnd: "2024-02-14T16:34:09.000000Z",
		messages: [
			{
				id: 1,
				type: "text",
				message: "Привет",
				userId: 1,
				isReceived: true,
				isViewed: true,
				isUnread: false,
				date: "14.02.2024 15:12",
			},
			{
				id: 2,
				type: "text",
				message: "Принимаете заказ?",
				userId: 1,
				isReceived: false,
				isViewed: false,
				isUnread: true,
				date: "14.02.2024 15:12",
			},
		],
	},
];
